### PR TITLE
Added compablity table at readme.md

### PR DESCRIPTION
**Pull request by stamepicmorg**
After #25 PR I think this info will be useful if this table will be presented in readme.md.

## Example:

:x: - OS is not supported :heavy_check_mark: - OS is supported 

| Game \ Mod | Windows  | Linux   | Comment
| ------------- | ------| ------|------|
| <...>
| [Half-Life](http://store.steampowered.com/app/70/HalfLife/) | :heavy_check_mark: | :heavy_check_mark: | Also supported [Bugfixed and improved HL release](https://github.com/LevShisterov/BugfixedHL).
| [Half-Life: Decay](http://www.moddb.com/mods/half-life-decay/downloads/) | :heavy_check_mark: | :x: | Have no linux binary.
| <...>
| etc

### CODE REVIEW

**Comment by stamepicmorg** [comment]
@In-line, @theAsmodai. @s1lentq 

guys what do u think ?

**Comment by Phantomsq** [comment]
@stamepicmorg, I think they are just sleeping now 🌑🌙✨

**Comment by theAsmodai** [comment]
👍

**Comment by stamepicmorg** [comment]
Table is already done 😄

**Comment by Aleks-Z** [comment]
Thanks u, guys 😆

**Comment by stamepicmorg** [comment]
@Aleks-Z thank u for helping me with testing ❤️

**Pull request merged**
